{% set version = "0.8.1" %}

package:
  name: betamax
  version: {{ version }}

source:
  url: https://github.com/sigmavirus24/betamax/archive/{{ version }}.tar.gz
  sha256: 69b4e14e36273211e5a392da5c9ed572dd8b0c446b35204f57dca81765ed2fc1

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests >=2.0

test:
  imports:
    - betamax
    - betamax.cassette
    - betamax.matchers
    - betamax.serializers

about:
  home: https://github.com/sigmavirus24/betamax
  license: Apache-2.0
  summary: 'A VCR imitation for python-requests.'

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
