{% set name = "betamax" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/betamax-{{ version }}.tar.gz
  sha256: 82316e1679bc6879e3c83318d016b54b7c9225ff08c4462de4813e22038d5f94

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.0

test:
  imports:
    - betamax
    - betamax.cassette
    - betamax.matchers
    - betamax.serializers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sigmavirus24/betamax
  license: Apache-2.0
  license_file: LICENSE
  summary: 'A VCR imitation for python-requests.'

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
