{% set version = "0.9.0" %}

package:
  name: betamax
  version: {{ version }}

source:
  url: https://github.com/sigmavirus24/betamax/archive/{{ version }}.tar.gz
  sha256: 971bcaffce5ce8fdc67fb207fb0d12657d2ac169e0086428b5acdf8d54d8a8d5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests >=2.0

test:
  imports:
    - betamax
    - betamax.cassette
    - betamax.matchers
    - betamax.serializers

about:
  home: https://github.com/sigmavirus24/betamax
  license: Apache-2.0
  license_file: LICENSE
  summary: 'A VCR imitation for python-requests.'

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
