travis:
  secure:
    BINSTAR_TOKEN: UY443TMzBEO7STQOKGCLBmv0ckWDa0zVKZ0hGWqX/0cQcz4ibM+yKaNtzdx0x8/QVHMbZJAg0OzOBXHwpeQqMzX1BV7RUIFCOGcvKkSVxTTqNFsu2kTcjOC3AOaluW7X0gF/ugWw6TMswdB+1JxS1ObRbBZs6zTMnJ7PBGanICrUS9DTDvzK31Tcr2UVS+FdrnN6SeQ8l53I2EFT9ryUcD+IXTa4gTj9mm4cCILGBV6CRUiIKICg2HE39Mvskim3MpJ69oxpMZTDU7yTipIrtBLjbsAVbJWcLN12qA/AHiaKsoZkjvClxTJDOQAq8bF7HM4JewRsfY1WwLDeogXJvZpwOJRdMEBsEJ39KnmpQg2Uo/EAEIRbi0QpfaPQsAeu2JEj34KaZivUnYq/+rJ4huEE5ThOqRAFy93jwVQK//ae7ZNTnB1t8xU9ouH6PYr5klWaSaA3ZhoY+88C4UUdj662yjAkDELbhiVG2F47Z1TIJ2CCL8q0IEmHdMKeSb0hOMbL9A8WHbofXv4TzWPjxjOzCaZrQOoUnuqRVIwPTc/Y4wSebcgA+68TnI+sBoTGnvz/Jo4aROaSRRItIyi0m4+NYcjUt6b0Dz/XiB3FwxiM9p+euZ4Lw19kPjMrssbqjT0BihYoOGxEjmk8J5PI1q/DA3DA2MUGGv53Iwd9tkU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
