travis:
  secure:
    BINSTAR_TOKEN: VwUiyT0tF4V0pVAnomfnVyD9gr5nM7AwQpO0osd4fEaJhICDlwwP+SL1xF1DyXoFlwJXXkZ18KiDKfhBuyN9RS+lXA0yysm+sDkDQuYStJesA7jbht7YmwtfWO2LPAAjVme8U9BajRStTPqUvfpUeOa5KgSzxq0OKot+CLtRsq/+MIjOADgNp2GwOAkZucs04+GO+QXhbaE5msOO81NJtycH73HXg9aJgjFmyVqqWd/V8sNj/Ah+TjpkrbPWnZCBfG/bKGk41Mn56TngLMheH8BCWBvEeyVyK5C8a7ryfbdL832c3f1hOiw6JSVRz62R0C5rObY0mlV28NO4TLuyXatFuXsHyvrjJ2JvquYR6h5o5X1iIQPiHCaEgscEeLf+261fPClrkk0M9S467zIHVWnI5yTMcOlyGuKZUiFH+/k+SA4/iGtWNq+ulqfGRKX1wa5o3+QU6cu3oG9jlcDL7jDojusY0kxvIPW3V2Sxyogpj4aR4gqaXYTkdmEmRAylzNrsbMmNw+B+Irlu7gEzVk6O4cvAOuxnsbhmzu9Kh2tzWeeQEbLQ1dZCW4x43sy9iDYQg+F5ITMBKtJFfMVW9k8muLusQozxq3aJ596PuNtvxtkgVPXWCLGDJG9DZJ9q/I9vdHMFnGLLvc+Cnrvswoh4VRM5cW8UG46TqkX5CCE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
